options(stringsAsFactors=F)
library(data.table)
setwd('<PROJECT_ROOT>')
rm(list=ls())
ref <- read.csv('Full_Clinical_Dataset.csv')
sam <- read.delim("data_clinical_sample_v1.txt")
dat <- subset(ref, MolecularSubtype == 'MSS')
pri <- subset(dat, mCRCType == 'Early Stage Primary')
pri <- subset(pri, StageatDiagnosis != 'IV' & is.na(Timetometastasis.months.))
pri_check <- subset(sam, MOLECULAR_SUBTYPE=='MSI Status' & MCRC_TYPE=='Early Stage Primary')
write.table(pri, file = 'MSK2017_Early_stage_primaries_sampleID.txt',row.names=F,quote=F,sep='\t')
pri <- subset(dat, mCRCType == 'mCRC Primary')
pri_check <- subset(sam, MOLECULAR_SUBTYPE=='MSI Status' & MCRC_TYPE=='mCRC Primary')
write.table(pri, file = 'MSK2017_mCRC_primaries_sampleID.txt',row.names=F,quote=F,sep='\t')
pri <- subset(dat, mCRCType == 'mCRC Metastasis')
pri_check <- subset(sam, MOLECULAR_SUBTYPE=='MSI Status' & MCRC_TYPE=='mCRC Metastasis')
write.table(pri, file = 'MSK2017_mCRC_Metastasis_sampleID.txt',row.names=F,quote=F,sep='\t')
options(stringsAsFactors=F)
library(data.table)
setwd('<PROJECT_ROOT>')
rm(list=ls())
ref <- read.csv('Full_Clinical_Dataset.csv')
sam <- read.delim("data_clinical_sample_v1.txt")
dat <- subset(ref, MolecularSubtype == 'MSS')
pri <- subset(dat, mCRCType == 'mCRC Primary' & Peritoneum.omentum.abdomen.FirstSiteofMetastasis==1)
pri_check <- subset(sam, MOLECULAR_SUBTYPE=='MSI Status' & MCRC_TYPE=='mCRC Primary' & METASTASES_SITE_FIRST_PERITONEUM_OMENTUM_ABDOMEN==1)
write.table(pri, file = 'MSK2017_mCRC.PERITONEUM.OMENTUM.ABDOMEN_primaries_sampleID.txt',row.names=F,quote=F,sep='\t')
pri <- subset(dat, mCRCType == 'mCRC Metastasis')
pri <- subset(pri, MetastaticTumorBiopsySite %in% c('Abdomen','Abdominal Wall','Omentum','Peritoneal Fluid','Peritoneal Implant','Peritoneal implant on Sigmoid Colon','Peritoneum','RetroPeritoneum'))
pri_check <- dat[c(grep('abdom',tolower(dat$MetastaticTumorBiopsySite)),
                   grep('omen',tolower(dat$MetastaticTumorBiopsySite)),
				   grep('perit',tolower(dat$MetastaticTumorBiopsySite))
				   ),]
write.table(pri, file = 'MSK2017_mCRC.PERITONEUM.OMENTUM.ABDOMEN_Metastasis_sampleID.txt',row.names=F,quote=F,sep='\t')
options(stringsAsFactors=F)
library(data.table)
setwd('<PROJECT_ROOT>')
rm(list=ls())
ref <- read.csv('Full_Clinical_Dataset.csv')
sam <- read.delim("data_clinical_sample_v1.txt")
dat <- subset(ref, MolecularSubtype == 'MSS' & mCRCType == 'Early Stage Primary')
mm <- read.delim('MSK2017_mCRC_Metastasis_sampleID.txt')
mp <- read.delim('MSK2017_mCRC_primaries_sampleID.txt')
pri <- subset(dat, ! PatientID %in% c(mp$PatientID, mm$PatientID))
pri <- subset(pri, StageatDiagnosis %in% c('I','II'))
pri <- subset(pri, is.na(Timetometastasis.months.))
pri <- subset(pri, SurvivalDateofdxtodateofdeathorlastFUforearlystageprimary.months. >= 24 & VitaLStatus=="Living")
write.table(pri, file='MSK2017_Early_stage_primaries_2yr.follow.up_sampleID.txt', row.names=F,quote=F,sep='\t')
