options(stringsAsFactors=F)
library(data.table)
setwd('<PROJECT_ROOT>')
rm(list=ls())
mp <- read.delim('MSK2017_mCRC.PERITONEUM.OMENTUM.ABDOMEN_primaries_sampleID.txt')
mm <- read.delim('MSK2017_mCRC.PERITONEUM.OMENTUM.ABDOMEN_Metastasis_sampleID.txt')
id <- rbind(mp,mm)
cnv <- read.delim('data_cna_hg19.seg')
cnv_mcrc <- subset(cnv, ID %in% id$SampleID)
cnv_mcrc_unique <- subset(cnv_mcrc,!duplicated(cnv_mcrc))
write.table(cnv_mcrc_unique, file='MSK_mCRC_Abdomen.Metastasis_data_cna_hg19.seg',row.names=F,quote=F,sep='\t')
rm(list=ls())
ep <- read.delim("MSK2017_Early_stage_primaries_sampleID.txt")
cnv <- read.delim('data_cna_hg19.seg')
cnv_ep <- subset(cnv, ID %in% ep$SampleID)
cnv_ep_unique <- subset(cnv_ep,!duplicated(cnv_ep))
write.table(cnv_ep_unique, file='MSK_mCRC_Early.Primary_data_cna_hg19.seg',row.names=F,quote=F,sep='\t')
options(stringsAsFactors=F)
library(data.table)
setwd('<PROJECT_ROOT>')
rm(list=ls())
sam <- read.delim('TCGA_COADREAD_StageI-III_MSS_sampleID.txt')
cnv <- read.delim('data_cna_hg19.seg')
cnv$ID <- substr(cnv$ID, 1, 12)
cnv1 <- subset(cnv, ID %in% sam$PATIENT_ID)
write.table(cnv1, file='TCGA_COADRED_EarlyPrimary_data_cna_hg19.seg',row.names=F,quote=F,sep='\t')
options(stringsAsFactors=F)
library(data.table)
setwd('<PROJECT_ROOT>')
rm(list=ls())
tcga <- read.delim('TCGA_COADRED_EarlyPrimary_data_cna_hg19.seg')
msk <- read.delim('../crc_msk_2017/MSK_mCRC_Early.Primary_data_cna_hg19.seg')
cnv <- rbind(tcga, msk)
write.table(cnv, file='TCGA.COADRED_plusMSK_EarlyPrimary_data_cna_hg19.seg',row.names=F,quote=F,sep='\t')
