setwd('<PROJECT_ROOT>')
options(stringsAsFactors=F)
library(data.table)
ano <- read.delim('OncoKB_data_all.txt',sep='$')
ano$gene <- toupper(gsub(' ','',ano$gene))
dat <- read.delim('NJMU_mCRC_ALL_Sample_mutation.maf')
dat$gene <- sapply(strsplit(dat$mutation_id,':'),'[',1)
dat$gene <- toupper(gsub(' ','',dat$gene))
dat$Variant_Classification <- sapply(strsplit(dat$mutation_id,':'),'[',2)
nsyv <- c('Frame_Shift_Del','Frame_Shift_Ins','In_Frame_Del','In_Frame_Ins','Missense_Mutation','Nonsense_Mutation','Nonstop_Mutation','Splice_Site')
dat <- subset(dat, Variant_Classification %in% nsyv)
dat1 <- subset(dat, gene %in% ano$gene)
maf <- read.delim('NJMU_mCRC_ALL_Sample_mutation_annotation.maf')
maf$ID <- paste(maf$mutID, maf$Normal, gsub('_','-',maf$Class_a), sep='_')
dat1$ID <- paste(dat1$mutation_id, dat1$Normal, dat1$sample_id, sep='_')
data <- merge(dat1[,c('mutation_id','cluster_id','cellular_prevalence','cellular_prevalence_std','variant_allele_frequency','ID')], maf, by='ID')
write.csv(data,file='NJMU_mCRC_drug_target_for_OncoKB_Annotation.csv',row.names=F,quote=F)
