setwd('<PROJECT_ROOT>')
options(stringsAsFactors=F)
library(data.table)
rm(list=ls())
dat <- read.delim('NJMU_mCRC_ALL_Sample_mutation.maf')
dat$gene <- sapply(strsplit(dat$mutation_id,':'),'[',1)
dat$gene <- toupper(gsub(' ','',dat$gene))
dat$Variant_Classification <- sapply(strsplit(dat$mutation_id,':'),'[',2)
nsyv <- c('Frame_Shift_Del','Frame_Shift_Ins','In_Frame_Del','In_Frame_Ins','Missense_Mutation','Nonsense_Mutation','Nonstop_Mutation','Splice_Site')
dat <- subset(dat, Variant_Classification %in% nsyv)
maf <- read.delim('NJMU_mCRC_ALL_Sample_mutation_annotation.maf')
maf$ID <- paste(maf$mutID, maf$Normal, gsub('_','-',maf$Class_a), sep='_')
dat$ID <- paste(dat$mutation_id, dat$Normal, dat$sample_id, sep='_')
data <- merge(dat[,c('mutation_id','cluster_id','cellular_prevalence','cellular_prevalence_std','variant_allele_frequency','ID')], maf, by='ID')
data$gene_pro <- toupper( paste(data$Hugo_Symbol, substr(gsub('p.','',data$Protein_Change),1,2),sep='_' ))
ano <- read.delim('Actionability_AllData_v9_GRCh37.tsv')
ano$gene <- toupper(gsub(' ','',ano$GENE))
ano$mutation_remark <- toupper(gsub(' ','',ano$MUTATION_REMARK))
gene_list <- unique(data$gene_pro)
target_gene <- c()
rownum <- c()
for(g in gene_list){
	rownum_g1 <- grep(g, ano$MUTATION_AA_SYNTAX)
	rownum_g2 <- grep(g, ano$mutation_remark)
	rownum <- c(rownum, rownum_g1, rownum_g2)
	if(length(unique(c(rownum_g1, rownum_g2)))>0){
		target_gene <- c(target_gene, g)
	}
	rm(rownum_g1, rownum_g2, g)
}
ano <- ano[unique(rownum),]
write.table(ano, file='COSMIC_Actionability_AllData_v9_GRCh37_selected_mNJMU.tsv',row.names=F,quote=F,sep='\t')
dat1 <- subset(data, gene_pro %in% unique(target_gene))
write.csv(dat1,file='NJMU_mCRC_drug_target_for_COSMIC_Annotation.csv',row.names=F,quote=F)
