options(stringsAsFactors=F)
setwd('<PROJECT_ROOT>')
rm(list=ls())
dat <- read.table('../6_Met_driver_genes_update/CNV_paired_test/mCRC_SCNA_gene_sample.bed')
ano <- read.delim('OncoKB_data_all.txt',sep='$')
ano$gene <- toupper(gsub(' ','',ano$gene))
dat$gene <- toupper(dat$V6)
ano <- subset(ano, gene %in% dat$gene)
cnv <- unique(c(grep('AMP',toupper(ano$alt)),grep('DEL',toupper(ano$alt))))
ano <- ano[cnv,]
dat1 <- subset(dat,gene%in%ano$gene)
write.csv(dat1,file='NJMU_mCRC_CNV_for_OncoKB_Annotation.csv',row.names=F,quote=F)
write.table(ano,file='OncoKB_selected_AMP.DEL_Annotation.txt',row.names=F,quote=F,sep='$')
options(stringsAsFactors=F)
setwd('<PROJECT_ROOT>')
rm(list=ls())
dat <- read.table('../6_Met_driver_genes_update/CNV_paired_test/mCRC_SCNA_gene_sample.bed')
ano <- read.delim('Actionability_AllData_v9_GRCh37.tsv')
dat1 <- subset(dat, V6 %in% ano$GENE)
write.csv(dat1,file='NJMU_mCRC_CNV_for_COSMIC_Annotation.csv',row.names=F,quote=F)
write.table(ano,file='COSMIC_selected_AMP.DEL_Annotation.txt',row.names=F,quote=F,sep='$')
