options(stringsAsFactors=F)
setwd('<PROJECT_ROOT>')
library(data.table)
rm(list=ls())
sam <- read.csv('SampleInformation.final.csv')
sam <- subset(sam, !is.na(Purity) & !is.na(Ploidy))
id <- read.csv('../Clonevol_sample_used.csv')
sam <- subset(sam, paste(Normal,Class_a) %in% paste(id$Normal,id$Class_a))
sam$id <- paste(sam$Normal, sam$Class_a,sep='_')
dat <- read.csv('../Clonevol_sample_used_reName.csv')
dat$id <- paste(dat$Normal, dat$Class_a,sep='_')
data <- merge(dat,sam,by='id')
data$tumor <- sapply(strsplit(data$sam_name,' '),'[',1)
data$region <- sapply(strsplit(data$sam_name,' '),'[',2)
write.csv(data,file='Table_s2_sample_info.csv',row.names=F,quote=F)
